name: HACS Action

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  hacs:
    name: HACS Action
    runs-on: "ubuntu-latest"
    timeout-minutes: 10
    steps:
      - name: HACS Action
        uses: "hacs/action@main"
        with:
          category: "integration"
